extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
env:
  es6: true
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-var:
    - error
  prefer-const:
    - error
  comma-dangle:
    - error
    - always-multiline
  one-var:
    - error
    - never
  arrow-parens:
    - error
    - always
  curly:
    - error
    - multi-line
  eqeqeq:
    - error
  spaced-comment:
    - error
    - always
  no-trailing-spaces:
    - error
  no-console:
    - error
  no-shadow:
    - error
