extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
env:
  es6: true
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-var:
    - error
  prefer-const:
    - error
  comma-dangle:
    - error
    - always-multiline
  one-var:
    - error
    - never
  arrow-parens:
    - error
    - always
  curly:
    - error
    - multi-line
  eqeqeq:
    - error
  spaced-comment:
    - error
    - always
  no-trailing-spaces:
    - error
  no-console:
    - error
  no-shadow:
    - error
  object-curly-spacing:
    - error
    - always
overrides:
  - files:
    - '*.ts'
    - '*.tsx'
    rules:
      no-shadow: # must use the TS-specific rule instead
        - off
      '@typescript-eslint/no-shadow':
        - error
      '@typescript-eslint/no-unused-vars':
        - error
        - ignoreRestSiblings: true
  - files:
    - '*.tsx'
    rules:
      react/prop-types:
        - off # using Typescript so it's unnecessary
